name: kukelola_flutter
description: KuKelola Apps Created With Flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  get: ^4.1.1
  intl: ^0.17.0
  dio: ^4.0.0
  archive: ^2.0.0
  connectivity: ^3.0.3
  shared_preferences: ^2.0.5
  flutter_staggered_grid_view: ^0.3.4
  cached_network_image:
  division: ^0.8.8
  firebase_messaging: ^7.0.3
  flutter_local_notifications:
  auto_size_text: ^2.1.0
  flutter_screenutil: ^4.0.3+2
  flutter_svg: ^0.19.3
  flutter_keyboard_visibility: ^4.0.4
  flutter_datetime_picker: ^1.5.0
  file_picker: 2.0.7
  table_calendar: ^2.3.3
  google_maps_flutter: ^1.2.0
  geolocator: ^6.2.1
  open_file: ^3.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_launcher_icons: ^0.8.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path_android: "assets/images/kukelola_logo_android.png"
  image_path_ios: "assets/images/kukelola_logo_ios.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Biryani
      fonts:
        - asset: assets/fonts/Biryani-Heavy.otf
          weight: 900
        - asset: assets/fonts/Biryani-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Biryani-Bold.otf
          weight: 700
        - asset: assets/fonts/Biryani-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Biryani-Regular.otf
          weight: 400
        - asset: assets/fonts/Biryani-Light.otf
          weight: 300
        - asset: assets/fonts/Biryani-UltraLight.otf
          weight: 200
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100